#!/usr/bin/env bash
# OpsRoom installer — from a bare Ubuntu box to a welcome screen.
#
#   curl -fsSL <hosted-url>/install.sh | sudo bash
#   sudo bash install.sh
#   sudo OPSROOM_PULL_TOKEN=... TS_AUTHKEY=tskey-auth-... bash install.sh   # unattended
#   sudo bash install.sh --token-file /path/to/token                        # token w/o env or tty
#
# It asks for TWO things — a registry pull token and a Tailscale auth key —
# then joins the tailnet, pulls the released images (NOTHING is built on
# this box), and prints a URL. THEN IT EXITS. The rest happens in your
# browser: open the URL, fill the setup form, watch it install, land on
# the login. A dropped SSH connection cannot kill the install — it does
# not run in your session.
#
# Other modes:
#   sudo bash install.sh --upgrade    # git pull + pull + up, gated by upgrades.json
#   sudo bash install.sh --fresh      # wipe THIS project (containers+volumes+config) for a clean re-run
#
# The product arrives as pulled, signed images pinned by release.env.
# This repo is public and contains no secrets — every credential is
# generated on your box or typed into the form by you.

set -euo pipefail

REPO_HTTPS="${OPSROOM_DEPLOY_REPO:-https://github.com/algoradev/opsroom-deploy.git}"
REGISTRY_HOST="ghcr.io"          # must match release.env's OPSROOM_REGISTRY host
REGISTRY_NS="algoradev"
OPS_USER="${OPSROOM_USER:-opsroom}"
SETUP_PORT="${OPSROOM_SETUP_PORT:-8100}"
STATUS_FILE="/run/opsroom-setup.status"
INSTALL_LOG="/var/log/opsroom-install.log"
SETUP_DIR="/opt/opsroom-setup"
TS_HOSTNAME="${OPSROOM_TS_HOSTNAME:-opsroom}"

say()  { printf '\033[1;35m==>\033[0m %s\n' "$*"; }
ok()   { printf '    \033[32m✓\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" = 0 ] || die "run as root: sudo bash install.sh"
[ -r /etc/os-release ] || die "cannot read /etc/os-release"
. /etc/os-release
case "${ID:-}" in ubuntu|debian) ;; *) die "Ubuntu/Debian only (found ${ID:-unknown})";; esac
export DEBIAN_FRONTEND=noninteractive

note() { printf '%s\n' "$1" > "$STATUS_FILE"; }

# ════════════════════════════════════════════════════════════════════════
# DEPLOY PHASE — invoked by the setup server AFTER the form is submitted,
# detached from any terminal, writing a one-line status the browser polls.
#   install.sh --deploy <repo_dir> <answers.json> <ts_dns> <ops_user>
# The sequence below is not designed — it is TRANSCRIBED from the slice-1
# boot proof that ran it (product repo, reports/142 OUTCOME).
# ════════════════════════════════════════════════════════════════════════
if [ "${1:-}" = "--deploy" ]; then
  REPO_DIR="$2"; ANSWERS="$3"; TS_DNS="$4"; OPS_USER="${5:-opsroom}"
  HOME_DIR=$(getent passwd "$OPS_USER" | cut -d: -f6)
  cd "$REPO_DIR"
  dfail() { note "error:$1"; exit 1; }
  # NEVER die silently: set -e exits with NO message; the trap turns any
  # unhandled failure into a recorded error the browser shows.
  trap 'note "error:step failed at line $LINENO: ${BASH_COMMAND}"; exit 1' ERR
  j() { python3 -c "import json,sys;print(json.load(open(sys.argv[1])).get(sys.argv[2],''))" "$ANSWERS" "$1"; }
  run() { sudo -u "$OPS_USER" env PATH="/usr/local/bin:$PATH" HOME="$HOME_DIR" "$@"; }
  # release.env (tracked pin) first, .env (yours) second — later wins.
  DC="docker compose --env-file release.env --env-file .env"
  rnd() { openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | cut -c1-32; }

  note "installing:writing configuration"
  ADMIN_USER=$(j admin_user); ADMIN_PASS=$(j admin_pass)
  # Idempotency (contract 141 §5): check-then-act against BOTH .env and
  # volume state. A half-done box resumes or refuses loudly — never
  # regenerates secrets over an initialized database.
  if [ -f .env ] && docker volume inspect opsroom_postgres-data >/dev/null 2>&1; then
    note "installing:resuming with the existing configuration"
  elif [ -f .env ]; then
    dfail ".env exists but the database volumes do not — unknown half-state. Run: sudo bash install.sh --fresh"
  else
    {
      printf '# generated by install.sh %s — do not commit\n' "$(date -u +%FT%TZ)"
      printf 'TAILSCALE_HOST=%s\n' "$TS_DNS"
      printf 'OPSROOM_PUBLIC_ORIGIN=https://%s\nOPSROOM_PUBLIC_URL=https://%s\n' "$TS_DNS" "$TS_DNS"
      printf 'POSTGRES_SUPERUSER=postgres\nPOSTGRES_SUPERUSER_PASSWORD=%s\n' "$(rnd)"
      printf 'APP_DB_NAME=asunset\nAPP_DB_OWNER=asunset_owner\nAPP_DB_OWNER_PASSWORD=%s\n' "$(rnd)"
      printf 'APP_DB_USER=asunset\nAPP_DB_PASSWORD=%s\n' "$(rnd)"
      printf 'KC_DB_NAME=keycloak\nKC_DB_USER=keycloak\nKC_DB_PASSWORD=%s\n' "$(rnd)"
      printf 'FGA_DB_NAME=openfga\nFGA_DB_USER=openfga\nFGA_DB_PASSWORD=%s\n' "$(rnd)"
      printf 'KEYCLOAK_REALM=asunset\nKEYCLOAK_ADMIN=admin\nKEYCLOAK_ADMIN_PASSWORD=%s\n' "$(rnd)"
      printf 'KEYCLOAK_API_CLIENT_SECRET=%s\nOPENFGA_API_KEY=%s\n' "$(rnd)" "$(rnd)"
      printf 'KEYCLOAK_EXTRA_AUDIENCES=opsroom-api,opsroom-mcp,orchestration\n'
      printf 'OPSROOM_PG_PASSWORD=%s\n' "$(rnd)"
      # Enforced from FIRST boot — the api's lifespan bootstraps the
      # authorization store only when enforcing (boot-proof lesson).
      printf 'OPSROOM_ENV=production\nOPSROOM_AUTH_ENFORCE=true\n'
      printf 'INVITE_DELIVERY=%s\nMCP_BEARER=%s\n' "$(j invite_mode)" "$(openssl rand -base64 48 | tr -d '/+=\n' | cut -c1-48)"
      printf 'OPSROOM_BACKUP_DEST=s3://%s\nOPSROOM_BACKUP_S3_ENDPOINT=%s\n' "$(j backup_bucket)" "$(j s3_endpoint)"
      printf 'OPSROOM_BACKUP_S3_ACCESS_KEY_ID=%s\nOPSROOM_BACKUP_S3_SECRET_ACCESS_KEY=%s\n' "$(j s3_key)" "$(j s3_secret)"
      printf 'OPSROOM_BACKUP_PASSPHRASE=%s\nOPSROOM_BACKUP_RETAIN_DAYS=30\n' "$(j backup_pass)"
      printf 'OPSROOM_ORG=instance\nOPSROOM_TEAM=default\nOPSROOM_PROJECT=default\n'
      printf 'VECTOR_LOG_LEVEL=info\n'
    } > .env
    chown "$OPS_USER:$OPS_USER" .env; chmod 600 .env
  fi

  AGE_DIR="$HOME_DIR/.config/sops/age"; mkdir -p "$AGE_DIR"
  if [ "$(j age_mode)" = restore ]; then
    ( umask 077; j age_key > "$AGE_DIR/keys.txt" )
  elif [ -f "$AGE_DIR/keys.txt" ]; then
    # NEVER destroy an existing key on generate-mode: if it encrypted any
    # backup, deleting it is the disaster this project already lived once.
    dfail "an age key already exists on this box but the form chose Generate. Choose Restore, or wipe deliberately: sudo bash install.sh --fresh"
  else
    ( umask 077; age-keygen -o "$AGE_DIR/keys.txt" 2>/dev/null )
  fi
  chown -R "$OPS_USER:$OPS_USER" "$HOME_DIR/.config"
  shred -u "$ANSWERS" 2>/dev/null || rm -f "$ANSWERS"

  note "installing:starting the identity plane"
  run $DC up -d --wait --wait-timeout 900 postgres openfga keycloak vector >/dev/null 2>&1 || dfail "identity plane did not come up"
  note "installing:seeding keycloak"
  run $DC up -d --wait --wait-timeout 600 keycloak-init >/dev/null 2>&1 || true
  until [ "$(docker inspect "$(run $DC ps -aq keycloak-init)" --format '{{.State.Status}}' 2>/dev/null)" = exited ]; do sleep 2; done

  note "installing:configuring the realm"
  run ./bin/kc-session-lifespans.sh >/dev/null 2>&1 || true
  KA=$(grep '^KEYCLOAK_ADMIN=' .env | cut -d= -f2); KP=$(grep '^KEYCLOAK_ADMIN_PASSWORD=' .env | cut -d= -f2)
  kc() { docker exec -i "$(run $DC ps -q keycloak)" /opt/keycloak/bin/kcadm.sh "$@" 2>/dev/null; }
  kc config credentials --server http://localhost:8080/auth --realm master --user "$KA" --password "$KP"
  W=$(kc get clients -r asunset -q clientId=asunset-web --fields id --format csv --noquotes | tr -d '\r\n"')
  kc update "clients/$W" -r asunset -s 'attributes."oauth2.device.authorization.grant.enabled"=true'
  # The admin YOU chose, as platform_admin — no seeded users exist in this
  # realm export (they were stripped; the audit found them shipping with
  # working passwords).
  kc create users -r asunset -s "username=$ADMIN_USER" -s enabled=true -s emailVerified=true >/dev/null 2>&1 || true
  kc set-password -r asunset --username "$ADMIN_USER" --new-password "$ADMIN_PASS"
  AU=$(kc get users -r asunset -q "username=$ADMIN_USER" --fields id --format csv --noquotes | tr -d '\r\n"')
  kc update "users/$AU" -r asunset -s 'requiredActions=[]'
  kc add-roles -r asunset --uusername="$ADMIN_USER" --rolename=platform_admin || true
  run ./bin/realm-doctor.sh >/dev/null 2>&1 || dfail "realm is not coherent — check ./bin/realm-doctor.sh"

  note "installing:starting the product (pulled images — no build)"
  run $DC up -d --wait --wait-timeout 900 >/dev/null 2>&1 || dfail "the stack did not come up healthy"

  note "installing:creating the instance home"
  run $DC --profile ops run --rm --no-deps opsroom-init >>"$INSTALL_LOG" 2>&1 || dfail "opsroom-init failed — see $INSTALL_LOG"

  note "installing:identity-plane schema"
  # The asunset chain ships INSIDE the api image; run it from there with
  # the owner DSN (boot-proof discovery — no source tree needed).
  APP_OWNER=$(grep '^APP_DB_OWNER=' .env | cut -d= -f2); APP_OPW=$(grep '^APP_DB_OWNER_PASSWORD=' .env | cut -d= -f2)
  APP_DB=$(grep '^APP_DB_NAME=' .env | cut -d= -f2)
  run $DC run --rm --no-deps \
    --workdir /opt/opsroom/vendor/asunset/apps/api \
    -e ASUNSET_PG_DSN="postgresql://${APP_OWNER}:${APP_OPW}@postgres:5432/${APP_DB}" \
    -e DATABASE_URL="postgresql://${APP_OWNER}:${APP_OPW}@postgres:5432/${APP_DB}" \
    opsroom-api alembic upgrade head >>"$INSTALL_LOG" 2>&1 || dfail "identity schema failed — see $INSTALL_LOG"

  note "installing:first backup"
  run ./backup/backup.sh >>"$INSTALL_LOG" 2>&1 || note "installing:first backup FAILED (continuing — fix backups after login)"

  note "installing:final checks"
  if ! run $DC --profile ops run --rm opsroom-doctor >>"$INSTALL_LOG" 2>&1; then
    # Doctor is honest: pre-first-login it may report the org warns; a
    # FAIL beyond that is real. Surface it, do not bury it.
    note "installing:doctor reported problems — the instance is up; review $INSTALL_LOG after login"
    sleep 2
  fi
  mkdir -p /etc/opsroom
  { grep '^OPSROOM_TAG=' release.env; echo "DEPLOY_COMMIT=$(git -C "$REPO_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"; } > /etc/opsroom/versions

  note "done:https://${TS_DNS}/"
  sleep 5
  # ORDER MATTERS (measured, twice): kill the setup server by ITS OWN pid,
  # reset serve, then point :443 at the product.
  if [ -r "$SETUP_DIR/server.pid" ]; then kill "$(cat "$SETUP_DIR/server.pid")" 2>/dev/null || true; fi
  pkill -f "$SETUP_DIR/server.py" 2>/dev/null || true
  sleep 1
  tailscale serve reset >/dev/null 2>&1 || true
  tailscale serve --bg --https=443 localhost:5173 >/dev/null 2>&1 || true
  exit 0
fi

# ════════════════════════════════════════════════════════════════════════
# --fresh: wipe THIS project for a clean re-run. Containers, volumes, the
# generated .env, the setup dir. The age key requires its own consent.
# ════════════════════════════════════════════════════════════════════════
if [ "${1:-}" = "--fresh" ]; then
  HOME_DIR=$(getent passwd "$OPS_USER" | cut -d: -f6 || true)
  REPO_DIR="${HOME_DIR:-/home/$OPS_USER}/opsroom-deploy"
  say "wiping the opsroom project"
  if [ -d "$REPO_DIR" ]; then
    # compose must PARSE the file to run down; supply the guarded vars
    # from .env when it exists, throwaway values when it does not.
    if [ -f "$REPO_DIR/.env" ]; then
      (cd "$REPO_DIR" && docker compose --env-file release.env --env-file .env --profile ops down -v --remove-orphans 2>/dev/null) || true
    else
      (cd "$REPO_DIR" && env OPSROOM_ORG=x OPSROOM_PROJECT=x OPSROOM_TEAM=x \
         OPSROOM_PG_PASSWORD=x OPSROOM_PUBLIC_ORIGIN=x OPENFGA_API_KEY=x \
         APP_DB_NAME=x APP_DB_OWNER=x APP_DB_OWNER_PASSWORD=x \
         docker compose --env-file release.env --profile ops down -v --remove-orphans 2>/dev/null) || true
    fi
    rm -f "$REPO_DIR/.env"
  fi
  rm -rf "$SETUP_DIR"; rm -f "$STATUS_FILE"
  tailscale serve reset >/dev/null 2>&1 || true
  if [ -f "${HOME_DIR:-}/.config/sops/age/keys.txt" ]; then
    if [ "${2:-}" = "--and-the-age-key" ]; then
      shred -u "$HOME_DIR/.config/sops/age/keys.txt" 2>/dev/null || rm -f "$HOME_DIR/.config/sops/age/keys.txt"
      ok "age key destroyed (you said so explicitly)"
    else
      ok "age key KEPT ($HOME_DIR/.config/sops/age/keys.txt). If it encrypted any backup you still need it. To destroy: --fresh --and-the-age-key"
    fi
  fi
  ok "fresh. Re-run: sudo bash install.sh"
  exit 0
fi

# ════════════════════════════════════════════════════════════════════════
# --upgrade: auth first, snapshot before migrating, pull to completion
# before touching services (contract 141 §7).
# ════════════════════════════════════════════════════════════════════════
if [ "${1:-}" = "--upgrade" ]; then
  HOME_DIR=$(getent passwd "$OPS_USER" | cut -d: -f6)
  REPO_DIR="$HOME_DIR/opsroom-deploy"
  cd "$REPO_DIR" || die "no install at $REPO_DIR"
  run() { sudo -u "$OPS_USER" env PATH="/usr/local/bin:$PATH" HOME="$HOME_DIR" "$@"; }
  DC="docker compose --env-file release.env --env-file .env"
  say "1/6 registry auth"
  run docker pull -q "$(grep '^OPSROOM_REGISTRY=' release.env | cut -d= -f2)/opsroom-api:$(grep '^OPSROOM_TAG=' release.env | cut -d= -f2)" >/dev/null \
    || die "registry pull failed — is the token still valid? (docker login ${REGISTRY_HOST})"
  say "2/6 upgrade window (upgrades.json)"
  CUR_TAG=$(grep '^OPSROOM_TAG=' /etc/opsroom/versions 2>/dev/null | cut -d= -f2 || true)
  if grep -q '"breaking": *true' upgrades.json 2>/dev/null; then
    python3 - "$CUR_TAG" <<'PYEOF' || { printf 'Continue anyway? [y/N] '; read -r a </dev/tty; [ "$a" = y ] || exit 1; }
import json, sys
cur = sys.argv[1]
d = json.load(open("upgrades.json"))
bad = [e for e in d.get("entries", []) if e.get("breaking")]
if bad:
    print("BREAKING entries exist since your installed version (%s):" % (cur or "unknown"))
    for e in bad:
        print("  -", e.get("product_tag"), "|", e.get("notes", ""))
    sys.exit(1)
PYEOF
  fi
  say "3/6 pre-upgrade snapshot"
  mkdir -p backups
  STAMP=$(date -u +%Y%m%dT%H%M%SZ)
  run bash -c "$DC exec -T postgres pg_dumpall -U postgres | gzip > backups/pre-upgrade-identity-$STAMP.sql.gz"
  run bash -c "$DC exec -T opsroom-postgres pg_dumpall -U opsroom | gzip > backups/pre-upgrade-product-$STAMP.sql.gz"
  ok "backups/pre-upgrade-*-$STAMP.sql.gz"
  say "4/6 new orchestration"
  if grep -q '^OPSROOM_TAG=' .env 2>/dev/null; then
    echo "    ! your .env pins OPSROOM_TAG and OVERRIDES the tracked release pin — remove it unless this is a deliberate rollback hold"
  fi
  run git pull --ff-only
  say "5/6 pull to completion, then recreate"
  run $DC pull -q
  run $DC up -d --wait --wait-timeout 900
  say "6/6 doctor + record"
  run $DC --profile ops run --rm opsroom-doctor || echo "    ! doctor reported problems — investigate before calling this upgrade done"
  { grep '^OPSROOM_TAG=' release.env; echo "DEPLOY_COMMIT=$(git rev-parse --short HEAD)"; } > /etc/opsroom/versions
  docker image prune -f >/dev/null   # dangling only; OLD TAGGED images stay = your rollback
  ok "upgraded. Rollback: set OPSROOM_TAG=<previous> in .env (see versions.md), then: $DC pull && $DC up -d"
  exit 0
fi

if [ "${1:-}" = "--restore" ]; then
  die "--restore is not automated yet. The pieces exist: backup/restore-drill.sh proves a backup restores; the form's 'Restore an existing age key' mode re-keys a fresh install. Doc: README.md#restore"
fi

# ════════════════════════════════════════════════════════════════════════
# FRONT HALF — runs in your terminal, ends at a URL, then exits.
# ════════════════════════════════════════════════════════════════════════

# ── 1. the registry pull token, validated BEFORE anything is spent ─────────
PULL_TOKEN="${OPSROOM_PULL_TOKEN:-}"
if [ "${1:-}" = "--token-file" ] && [ -n "${2:-}" ]; then
  PULL_TOKEN=$(cat "$2") || die "cannot read token file $2"
fi
if [ -z "$PULL_TOKEN" ] && { : > /dev/tty; } 2>/dev/null; then
  printf 'Registry pull token (read-only; from your OpsRoom vendor): ' > /dev/tty
  IFS= read -rs PULL_TOKEN < /dev/tty; printf '\n' > /dev/tty
fi
[ -n "$PULL_TOKEN" ] || die "no pull token. Set OPSROOM_PULL_TOKEN=..., or use --token-file, for unattended runs."
say "registry"
RTOK=$(curl -fsS -u "x:$PULL_TOKEN" "https://${REGISTRY_HOST}/token?scope=repository:${REGISTRY_NS}/opsroom-api:pull&service=${REGISTRY_HOST}" \
  | python3 -c 'import sys,json;print(json.load(sys.stdin)["token"])' 2>/dev/null) || die "the registry rejected the token"
curl -fsS -o /dev/null -H "Authorization: Bearer $RTOK" \
  "https://${REGISTRY_HOST}/v2/${REGISTRY_NS}/opsroom-api/tags/list" \
  || die "token authenticates but cannot read images — it needs pull (read) access"
ok "token verified against ${REGISTRY_HOST}/${REGISTRY_NS}"

# ── 2. the tailscale key ───────────────────────────────────────────────────
TS_AUTHKEY="${TS_AUTHKEY:-}"
# `[ -r /dev/tty ]` LIES over non-interactive ssh — test an actual open.
if [ -z "$TS_AUTHKEY" ] && { : > /dev/tty; } 2>/dev/null; then
  printf 'Tailscale auth key (login.tailscale.com/admin/settings/keys — single-use, spent on join): ' > /dev/tty
  IFS= read -rs TS_AUTHKEY < /dev/tty; printf '\n' > /dev/tty
fi
TS_JOINED=$(command -v tailscale >/dev/null 2>&1 && tailscale status --json 2>/dev/null | python3 -c 'import sys,json; print(json.load(sys.stdin).get("BackendState",""))' 2>/dev/null || true)
if [ "$TS_JOINED" != Running ]; then
  [ -n "$TS_AUTHKEY" ] || die "no Tailscale auth key. Set TS_AUTHKEY=... for unattended runs."
  case "$TS_AUTHKEY" in tskey-*) ;; *) die "that does not look like a Tailscale auth key (expected tskey-...)";; esac
fi

# ── 3. the operator account ────────────────────────────────────────────────
say "operator account: $OPS_USER"
id "$OPS_USER" >/dev/null 2>&1 || useradd --create-home --shell /bin/bash "$OPS_USER"
getent group docker >/dev/null || groupadd docker
usermod -aG sudo,docker "$OPS_USER"
HOME_DIR=$(getent passwd "$OPS_USER" | cut -d: -f6)
mkdir -p "$HOME_DIR"; chown -R "$OPS_USER:$OPS_USER" "$HOME_DIR"; chmod 750 "$HOME_DIR"
ok "$OPS_USER in sudo, docker; owns $HOME_DIR"

# ── 4. tools ───────────────────────────────────────────────────────────────
say "tools"
apt-get update -qq
apt-get install -y -qq ca-certificates curl gnupg git openssl gpg unzip python3 age >/dev/null
if ! command -v docker >/dev/null; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL "https://download.docker.com/linux/${ID}/gpg" | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null
  systemctl enable --now docker >/dev/null 2>&1 || true
fi
ok "docker $(docker --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)"
if ! command -v aws >/dev/null; then
  curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o /tmp/awscliv2.zip
  (cd /tmp && unzip -q -o awscliv2.zip && ./aws/install --update >/dev/null 2>&1)
  rm -rf /tmp/aws /tmp/awscliv2.zip
fi
command -v tailscale >/dev/null || curl -fsSL https://tailscale.com/install.sh | sh >/dev/null 2>&1
for t in docker aws age-keygen openssl curl git python3 tailscale; do
  command -v "$t" >/dev/null || die "still missing after install: $t"
done
ok "every tool this repo's scripts call is on PATH"

# ── 5. the tailnet ─────────────────────────────────────────────────────────
say "tailnet"
TS_STATE=$(tailscale status --json 2>/dev/null | python3 -c 'import sys,json; print(json.load(sys.stdin).get("BackendState",""))' 2>/dev/null || true)
if [ "$TS_STATE" = Running ]; then
  tailscale set --hostname="$TS_HOSTNAME" >/dev/null 2>&1 || true
  sleep 2
  ok "already on the tailnet — key not needed"
else
  AKF=$(mktemp); chmod 600 "$AKF"; printf '%s' "$TS_AUTHKEY" > "$AKF"
  if ! TS_ERR=$(tailscale up --authkey="file:$AKF" --hostname="$TS_HOSTNAME" --ssh=false 2>&1); then
    shred -u "$AKF" 2>/dev/null || rm -f "$AKF"
    printf '%s\n' "$TS_ERR" | sed 's/^/    /' >&2
    die "tailscale up failed. Auth keys are single-use — a key from a previous run is spent; mint a fresh one."
  fi
  shred -u "$AKF" 2>/dev/null || rm -f "$AKF"
fi
TS_DNS=$(tailscale status --json | python3 -c 'import sys,json; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))' 2>/dev/null || true)
[ -n "$TS_DNS" ] || die "joined the tailnet but could not read Self.DNSName"
ok "https://${TS_DNS}/"

# ── 6. this repo (PUBLIC — no deploy keys, no auth) ────────────────────────
say "orchestration"
REPO_DIR="$HOME_DIR/opsroom-deploy"
if [ ! -d "$REPO_DIR/.git" ]; then
  sudo -u "$OPS_USER" git clone -q "$REPO_HTTPS" "$REPO_DIR" || {
    TARBALL="${REPO_HTTPS%.git}/archive/refs/heads/main.tar.gz"
    mkdir -p "$REPO_DIR" && curl -fsSL "$TARBALL" | tar -xz --strip-components=1 -C "$REPO_DIR" \
      || die "could not fetch the deploy repo (git and tarball both failed)"
    chown -R "$OPS_USER:$OPS_USER" "$REPO_DIR"
  }
else
  sudo -u "$OPS_USER" git -C "$REPO_DIR" pull --ff-only -q || true
fi
git config --system --add safe.directory "$REPO_DIR" 2>/dev/null || true
ok "$(cd "$REPO_DIR" && git log -1 --format='%h %s' 2>/dev/null | cut -c1-50 || echo tarball)"

# ── 7. login as the OPS USER + pull everything (no build, ever) ────────────
say "images"
printf '%s' "$PULL_TOKEN" | sudo -u "$OPS_USER" docker login "$REGISTRY_HOST" -u "${OPSROOM_PULL_USER:-$REGISTRY_NS}" --password-stdin >/dev/null \
  || die "docker login failed for the ops user"
# The compose file's ${VAR:?} guards protect RUNNING with unset values;
# pulling only needs the image refs, so the guarded non-pin vars get
# throwaway values here (the deploy phase generates the real ones).
( cd "$REPO_DIR" && sudo -u "$OPS_USER" env \
    OPSROOM_ORG=x OPSROOM_PROJECT=x OPSROOM_TEAM=x OPSROOM_PG_PASSWORD=x \
    OPSROOM_PUBLIC_ORIGIN=x OPENFGA_API_KEY=x \
    APP_DB_NAME=x APP_DB_OWNER=x APP_DB_OWNER_PASSWORD=x \
    docker compose --env-file release.env pull -q ) \
  || die "image pull failed — check the token and release.env's pin"
ok "all images pulled at $(grep '^OPSROOM_TAG=' "$REPO_DIR/release.env" | cut -d= -f2)"

# ── 8. serve the form, print the URL, and EXIT ─────────────────────────────
say "setup"
rm -rf "$SETUP_DIR"; mkdir -p "$SETUP_DIR"; chmod 700 "$SETUP_DIR"
cp "$REPO_DIR"/setup/index.html "$REPO_DIR"/setup/installing.html "$REPO_DIR"/setup/server.py "$SETUP_DIR"/
SELF_COPY="$SETUP_DIR/install.sh"; cp "$REPO_DIR/install.sh" "$SELF_COPY" 2>/dev/null || cp "$0" "$SELF_COPY"
ANSWERS="$SETUP_DIR/answers.json"
: > "$STATUS_FILE"; chmod 644 "$STATUS_FILE"
: > "$INSTALL_LOG"; chmod 644 "$INSTALL_LOG"
setsid python3 "$SETUP_DIR/server.py" "$SETUP_DIR" "$ANSWERS" "$SETUP_PORT" "$STATUS_FILE" "$SELF_COPY" "$REPO_DIR" "$TS_DNS" "$OPS_USER" "$INSTALL_LOG" \
  </dev/null >>"$INSTALL_LOG" 2>&1 &
sleep 1
tailscale serve --https=443 off >/dev/null 2>&1 || true
tailscale serve --bg --https=443 "http://127.0.0.1:${SETUP_PORT}" >/dev/null 2>&1 || die "tailscale serve failed"

ok "setup is ready"
cat <<EOF

    Open this on any device on your tailnet, and fill the form:

      https://${TS_DNS}/

    It installs itself from there — the page shows progress and drops you
    into OpsRoom when it is done. You can close this terminal; the install
    does not run in it. (Follow along if you like: tail -f $INSTALL_LOG)
EOF
